import type { NextPage } from 'next';
import Head from 'next/head';

import {
  About,
  Header,
  Hero,
  Projects,
  Skills,
  WorkExperience,
} from '../components';

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen overflow-scroll overflow-x-hidden z-0 snap-y snap-mandatory">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      <section id="experience" className="snap-start">
        <WorkExperience />
      </section>
      <section id="skills" className="snap-start">
        <Skills />
      </section>
      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Projects */}

      {/* Contact Me */}
    </div>
  );
};

export default Home;
